biber_ltd_core_bundles_product_management:
    pattern:  products/{sortcolumn}/{sortorder}/{product_number}
    defaults: { _controller: BiberLtdBundleContentManagementBundle:Manage:productList }

    pattern:  products/edit/{product_id_or_code}
    defaults: { _controller: BiberLtdBundleContentManagementBundle:Manage:productEdit }

    pattern:  products/new
    defaults: { _controller: BiberLtdBundleContentManagementBundle:Manage:productNew }
    pattern:  products/delete
    defaults: { _controller: BiberLtdBundleContentManagementBundle:Manage:productDelete }
    pattern:  product_categories/{sortcolumn}/{sortorder}/{page_number}
    defaults: { _controller: BiberLtdBundleContentManagementBundle:Manage:productCategoryList }
    pattern:  product_categories/edit/{id}
    defaults: { _controller: BiberLtdBundleContentManagementBundle:Manage:productCategoryEdit }
    pattern:  product_categories/new
    defaults: { _controller: BiberLtdBundleContentManagementBundle:Manage:productCategoryNew }
    pattern:  product_categories/delete
    defaults: { _controller: BiberLtdBundleContentManagementBundle:Manage:productCategoryDelete }
    pattern:  product_attributes/{sortcolumn}/{sortorder}/{page_number}
    defaults: { _controller: BiberLtdBundleContentManagementBundle:Manage:productAttributeList }
    pattern:  product_attributes/edit/{id}
    defaults: { _controller: BiberLtdBundleContentManagementBundle:Manage:productAttributeEdit }
    pattern:  product_attributes/new
    defaults: { _controller: BiberLtdBundleContentManagementBundle:Manage:productAttributeNew }
    pattern:  product_attributes/delete
    defaults: { _controller: BiberLtdBundleContentManagementBundle:Manage:productAttributeDelete }
    pattern: brand
    defaults: {_controller: BiberLtdBundleProductManagementBundle:Test:test}

    