services:
    productmanagement.model:
            class:        BiberLtd\Core\Bundles\ProductManagementBundle\Services\ProductManagementModel
            arguments:    [@kernel, "default", "doctrine"]